# typed: false
# frozen_string_literal: true

# Generated by dragoscv/axiom scripts/render-homebrew-formula.mjs — do not edit by hand.
class Axiom < Formula
  desc "Transactional write gate for coding agents (MCP server + CLI + hook)"
  homepage "https://dragoscv.github.io/axiom/"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/dragoscv/axiom/releases/download/v2.3.1/axiom-darwin-arm64"
      sha256 "b39cb82dc38025f09869c03d2a4861185c8c4bcd5ce955a9868f586faee8320f"
    end
    on_intel do
      url "https://github.com/dragoscv/axiom/releases/download/v2.3.1/axiom-darwin-x64"
      sha256 "b8b823a56302940ae30393a9ce7844433b44064808dd0ffbb22dbe1c55e3bc42"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dragoscv/axiom/releases/download/v2.3.1/axiom-linux-arm64"
      sha256 "2565e611caf4b7cc0afa47cb90672f4f7b05e9af9526da5656e36d8d94aa4708"
    end
    on_intel do
      url "https://github.com/dragoscv/axiom/releases/download/v2.3.1/axiom-linux-x64"
      sha256 "8efbea31da8c05abec9434d7bea9c8ddab14b895efc8bb64b90ddaeef7f04809"
    end
  end

  def install
    bin.install Dir["axiom-*"].first => "axiom"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/axiom --version")
  end
end
