# typed: false
# frozen_string_literal: true

# Generated by dragoscv/axiom scripts/render-homebrew-formula.mjs — do not edit by hand.
class Axiom < Formula
  desc "Transactional write gate for coding agents (MCP server + CLI + hook)"
  homepage "https://dragoscv.github.io/axiom/"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/dragoscv/axiom/releases/download/v2.4.0/axiom-darwin-arm64"
      sha256 "6998ef6b1a60e3ddf85c14822b5480b617c0393e72790bdfed9eb6f0eb489e2c"
    end
    on_intel do
      url "https://github.com/dragoscv/axiom/releases/download/v2.4.0/axiom-darwin-x64"
      sha256 "f6bc823922ddcc6e571686d371c60d3a81d1f9decd2989809450764ff1345d0e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dragoscv/axiom/releases/download/v2.4.0/axiom-linux-arm64"
      sha256 "a18d76319553727db4e5fbd5cf4ece1ca5d44b370f191e2cb08ba3a148a7ecda"
    end
    on_intel do
      url "https://github.com/dragoscv/axiom/releases/download/v2.4.0/axiom-linux-x64"
      sha256 "fe3e71aefd1880e09182864e5b899e7bacb8ba671fd6db189561e69818a07337"
    end
  end

  def install
    bin.install Dir["axiom-*"].first => "axiom"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/axiom --version")
  end
end
